"""Physical and unit conversion constants."""

STEFAN_BOLTZMANN_CONSTANT = 5.670374419e-8  # [W m−2 K−4]
SECONDS_PER_HOUR = 3600
SECONDS_PER_DAY = 86400
MILLIMETERS_PER_METER = 1000
MILLIMETERS_PER_HOUR_TO_METERS_PER_SECOND = (
    1.0 / SECONDS_PER_HOUR / MILLIMETERS_PER_METER
)
